global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'analyser'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/api/metrics'
    authorization:
      type: 'Bearer'
      credentials_file: '/etc/prometheus/secrets/metrics_token'
