global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'my-website'
    static_configs:
      - targets: ['nginx:80']  # Now targets nginx instead of host.docker.internal
    metrics_path: '/api/metrics'
    scrape_interval: 15s
