global:
  scrape_interval: 15s   # how often to scrape

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'my-website'
    static_configs:
      - targets: ['host.docker.internal:3000'] #targets can be changed based on way prometheus is installed on your system.
 