services:
  frontend:
    image: adishjain1107/analyser:latest
    container_name: nextjs-app
    restart: unless-stopped
    expose:
      - 3000
    env_file:
      - .env.production
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
